### ISSUE TITLE
Update to Python 3.8

### ISSUE THREAD

**Issue by thakyZ** [StarryPy/StarryPy3k#143]
So in the latest builds of Python, 3.8 and 3.9 the async functions have been rewritten, and I am to believe the whole code needs a rework. Currently the `@asyncio.coroutine` are not needed anymore and have been replaced with `async def function(self):`. But on top of that for every non-async function that called `yield from` cannot call that anymore and it seems that yield from cannot be used outside a async function anymore. So I am not sure what to use for that.

**Comment by jtwebhomer** [comment]
having this issue this causes permissions to break

**Comment by thakyZ** [comment]
Yea, StarrPy3k is completely incompatible with Python 3.7+ you have to use 3.6

**Comment by thakyZ** [comment]
I am still learning Async to be able to fix it up

**Comment by jtwebhomer** [comment]
i actually somehow got the permissions to work idk how tho and im
still using 3.8 but it is throwing errors i do think the mail commands
dont work at all

**Comment by thakyZ** [comment]
Well that's interesting...? Because from what I know, they more or less completely redid the Async functions in 3.8

**Comment by medeor413** [comment]
As far as I'm aware, there *shouldn't* be any issues preventing StarryPy from running, at least until Python 3.10 (when `@asyncio.coroutine` is being removed), but I haven't tested it, and I won't doubt something breaks somewhere.
Unfortunately, both me and @kharidiron are busy and not interested in updating the project. It should continue to remain fully functional, as long as it's run on Python 3.6, though.
I am still monitoring this repo, so if anyone wants to submit a pull request, I'll take a look. Otherwise, though, I wouldn't expect anything to happen here, unless Starbound gets a new update.

**Comment by daviirodrig** [comment]
I forked the repo to make it work in python 3.10 and changed some things: ([github comparison](https://github.com/StarryPy/StarryPy3k/compare/master...daviirodrig:StarryPy3k:refactor-python-3.10))

- Use `async def` and `await` instead of `@asyncio.coroutine` and `yield from`
- Folder structure to what I think is more organized
- Rewrote Dockerfile and added docker-compose
- Update other deprecated functions

Would you guys be interested in a pull request? Because this is a lot of changes and not every plugin works as of now I'd suggest to make a new branch, and then when possible we merge to master

Anyway, I will continue to update my fork whenever I have time.

**Comment by medeor413** [comment]
With #150 merged we're now running on Python 3.11. Should solve your issues.
