### ISSUE TITLE
UTF-8 characters support

### ISSUE THREAD

**Issue by Degranon** [StarryPy/StarryPy3k#81]
Hello!

That would be nice to have a utf-8 default encoding for chat manager and enchantment: we have a lot of Russian players with Cyrillic names and other players with non-ASCII characters.
So their names change from, for example, "Мария" to "8e73a", which is not nice surely.
Moreover, you can't use /nick with Unicode characters as it says that you didn't write any valid words.

**Comment by medeor413** [comment]
This is actually [intentional](https://github.com/StarryPy/StarryPy3k/commit/89991017b91e941e47230c389ee4d2936395791f); StarryPy filters a variety of characters, including non-ASCII ones, to make it easier for admins to type out player names and use commands on them. Now that players can be targetted by client id, though, this is less of a concern, and we could consider removing the non-ASCII filter.
